Add prototype of SQL statement
security-anthem/MAID pull request #17
Opened 2021-09-29 01:34 UTC by MMikipenguin

SQL文の宣言ファイルinit.pyを作りました．
わからない箇所はコメントに書きました．
第三正規形になるようDBを作りました．
間違っているかもしれないので，SQLや正規形に詳しい方に確認をいただきたいです．

ご確認よろしくお願いします．

2021-09-29 07:56 UTC, shu1oka28 commented
テーブルの作り方
======================

```json
{
    "received": [
        {
            "from": {
                "display": "mail.example.com",
                "reverse": "Unknown",
                "ip": "10.0.0.1"
            },
            "by": "mailsrv.example.com",
            "protocol": "ESMTP",
            "ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)",
            "spf": true,
            "dkim": true,
            "dmarc": false
        },
        {
            "from": {
                "display": "mail.example.com",
                "reverse": "Unknown",
                "ip": "10.0.0.1"
            },
            "by": "mailsrv.example.com",
            "protocol": "ESMTP",
            "ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)",
            "spf": true,
            "dkim": true,
            "dmarc": false
        }
    ],
    "title": "fuzzy hash",
    "attach": ["fuzzy hash of attachment1", "attachment2"],
    "pattern": ["service name 1", "service name 2"],
    "from": "",
    "reply-to": "",
    "subject": "hash"
}
```
例えば，otherという名前のtableを作ろうと思ったと仮定します．

関係「other」

|received|title|attach|pattern|from|reply-to|subject|
|:-------|:---|:-------|:-------|:-----|:-------|:-------|
| [{"from": {"display": "mail.example.com","reverse": "Unknown","ip": "10.0.0.1"},"by": "mailsrv.example.com","protocol": "ESMTP","ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)","spf": true,"dkim": true,"dmarc": false},{"from": {"display": "mail.example.com","reverse": "Unknown","ip": "10.0.0.1"},"by": "mailsrv.example.com","protocol": "ESMTP","ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)","spf": true,"dkim": true,"dmarc": false}], |"fuzzy hash"| ["fuzzy hash of attachment1", "attachment2"]|["service name 1", "service name 2"]|""|""|"hash"|

上記の表は配列の要素を含むため，「非正規形」です．
また，主キーのことを考えると，行を一意に定められる主キーにできそうな項目がないため，主キーとしてIDを追加します．
(RDBでは主キーは必須です）

|id(primary key)|received|title|attach|pattern|from|reply-to|subject|
|:--|:-------|:---|:-------|:-------|:-----|:-------|:-------|
|1| [{"from": {"display": "mail.example.com","reverse": "Unknown","ip": "10.0.0.1"},"by": "mailsrv.example.com","protocol": "ESMTP","ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)","spf": true,"dkim": true,"dmarc": false},{"from": {"display": "mail.example.com","reverse": "Unknown","ip": "10.0.0.1"},"by": "mailsrv.example.com","protocol": "ESMTP","ssl": "(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)","spf": true,"dkim": true,"dmarc": false}], |"fuzzy hash"| ["fuzzy hash of attachment1", "attachment2"]|["service name 1", "service name 2"]|""|""|"hash"|

receivedを別の表にする．
--------------------------
関係「received」に主キーにできそうな項目がないため，idをつけます．receivedのother_idがotherのidです．
otherとreceivedは1対多関係なので，多にあたるreceivedに外部キーother_idを設定します．
otherからreceivedという項目は消します．

関係「other」
|id(primary key)|title|attach|pattern|from|reply-to|subject|
|:--|:---|:-------|:-------|:-----|:-------|:-------|
|1 |"fuzzy hash"| ["fuzzy hash of attachment1", "attachment2"]|["service name 1", "service name 2"]|""|""|"hash"|


関係「received」
|id|other_id|from_display|from_reverse|from_ip|by|protocol|ssl|spf|dkim|dmarc|
|:--|:---|:------------|:-------------|:-------|:--|:--------|:--|:--|:----|:-------|
|1|1|mail.example.com|Unknown|10.0.0.1|mailsrv.example.com|ESMTP|(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)|true|true|false|
|2|1|mail.example.com|Unknown|10.0.0.1|mailsrv.example.com|ESMTP|(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)|true|true|false|

attachとpatternを別の表にする
----------------------------------
received，attach，patternはotherと1対多になっているので，received，attach，patternは，other_idとしてotherの主キーを外部キーとして格納する必要があります．このため，received，attach，patternには，other_idという項目を追加します．

関係「other」
|id(primary key)|title|from|reply-to|subject|
|:--|:---|:-------|:-------|:-------|
|1 |"fuzzy hash"|""|""|"hash"|

関係「received」
|id|other_id|from_display|from_reverse|from_ip|by|protocol|ssl|spf|dkim|dmarc|
|:--|:---|:------------|:-------------|:-------|:--|:--------|:--|:--|:----|:-------|
|1|1|mail.example.com|Unknown|10.0.0.1|mailsrv.example.com|ESMTP|(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)|true|true|false|
|2|1|mail.example.com|Unknown|10.0.0.1|mailsrv.example.com|ESMTP|(version=TLS1_2 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128)|true|true|false|

関係「attach」
|id|other_id|attach|
|:----|:------|:-----|
|1|1|"fuzzy hash of attachment1"|
|2|1|"attachment2"|

関係「pattern」
|id|other_id|pattern|
|:----|:------|:-------|
|1|1|"service name 1"|
|2|1|"service name 2"|

関係「received」と「attach」と「pattern」を別の表にすると，第3正規形の形になっているので，このまま表を確定にします．

2021-09-29 07:58 UTC, shu1oka28 requested changes
コメントにテーブルの要素の作り方をかきました。
テーブルの項目を見直して，SQL文を書き直してほしいです。

2021-09-29 13:22 UTC, MMikipenguin commented
ご指摘いただいた内容を参考にinit.pyを修正しました．

ご確認お願いします．

2021-09-30 01:54 UTC, shu1oka28 requested changes
`other`テーブルの型について，気になる点をコメントしました．

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  from varchar(100), -- mail's "from" information
`from`は予約語なので，`from_header`などに名前を変更した方がいいかもしれないです．

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  from varchar(100), -- mail's "from" information
`varchar(100)`では100バイトが限度になります．
メールアドレスは256文字くらいまで許容されており，Fromヘッダは`人の名前 <メールアドレス>`のようにさらに長くなると考えられます．とりあえず`varchar(500)`か制限文字数が無い`text`にしておくと良いと思います．

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  title int NOT NULL, -- fuzzy hash of mail's title
fuzzy hashは文字列として格納した方がいいのと，長さの上限が分からないので，`text`がいいと思います．
以下に文字列に関するpostgresqlの型のドキュメントのリンクを示します．
[https://www.postgresql.jp/docs/9.2/datatype-character.html](https://www.postgresql.jp/docs/9.2/datatype-character.html)

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  primary key(mail-id)
`mail-id`は，`m_id`のことでしょうか．

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  reply_to varchar(100), -- mail's "reply-to" information
14行目と同様に文字数制限が100バイト以内は厳しいと思います．

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  m_id int NOT NULL, -- id determins mail uniquely
`m_id`はプログラムで一意な値を指定するのは困難だと思うので，`serial`にするのはどうでしょうか．
[https://www.postgresql.jp/document/7.3/user/datatype.html#DATATYPE-NUMERIC-TABLE](https://www.postgresql.jp/document/7.3/user/datatype.html#DATATYPE-NUMERIC-TABLE)

2021-09-30 01:54 UTC, shu1oka28 commented on init.py
> +  subject int NOT NULL, -- hash of mail's subject
13行目と同様に今回のハッシュ値は数値ではなく文字列で扱いたいです．

2021-09-30 06:15 UTC, MMikipenguin commented
init.pyを修正しました．
ご指摘いただいた箇所を修正して，Ubuntuで動作することを確認しました．

ご確認お願い致します．

2021-09-30 06:33 UTC, shu1oka28 requested changes

2021-09-30 06:33 UTC, shu1oka28 commented on init.py
> +    cur.close()
71行目と72行目の間に`connection.commit()`を追記しないと作成したテーブルが保存されません．
追記してください．

2021-09-30 06:33 UTC, shu1oka28 commented on init.py
> +          title text NOT NULL, -- fuzzy hash of mail's title
下にsubjectがあったのでtitleいらなかったです．図を書いたときに誤りがありました．すみません．

2021-09-30 06:47 UTC, MMikipenguin commented
ご指摘いただいた3点（コネクションのコミット，「タイトル」メンバの除去，テーブル名「other」の変更）に関しまして，修正しました．

ご確認お願いします．

2021-09-30 06:58 UTC, shu1oka28 approved these changes
`python3 init.py`実行後にpsqlで結果を確認しました。問題ないと思います。
```
testdb=> \d overview
                                Table "public.overview"
   Column    |  Type   | Collation | Nullable |                Default                 
-------------+---------+-----------+----------+----------------------------------------
 m_id        | integer |           | not null | nextval('overview_m_id_seq'::regclass)
 from_header | text    |           |          | 
 reply_to    | text    |           |          | 
 subject     | text    |           | not null | 
Indexes:
    "overview_pkey" PRIMARY KEY, btree (m_id)
Referenced by:
    TABLE "attach" CONSTRAINT "attach_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)
    TABLE "pattern" CONSTRAINT "pattern_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)
    TABLE "received" CONSTRAINT "received_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)

testdb=> \d pattern
                              Table "public.pattern"
 Column  |  Type   | Collation | Nullable |                Default                
---------+---------+-----------+----------+---------------------------------------
 p_id    | integer |           | not null | nextval('pattern_p_id_seq'::regclass)
 m_id    | integer |           | not null | nextval('pattern_m_id_seq'::regclass)
 pattern | text    |           |          | 
Indexes:
    "pattern_pkey" PRIMARY KEY, btree (p_id)
Foreign-key constraints:
    "pattern_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)

testdb=> \d received
                                Table "public.received"
    Column    |  Type   | Collation | Nullable |                Default                 
--------------+---------+-----------+----------+----------------------------------------
 r_id         | integer |           | not null | nextval('received_r_id_seq'::regclass)
 m_id         | integer |           | not null | nextval('received_m_id_seq'::regclass)
 from_display | text    |           |          | 
 from_reverse | text    |           |          | 
 from_ip      | text    |           |          | 
 by           | text    |           |          | 
 protocol     | text    |           |          | 
 ssl          | text    |           |          | 
 spf          | bit(1)  |           |          | 
 dkim         | bit(1)  |           |          | 
 dmarc        | bit(1)  |           |          | 
Indexes:
    "received_pkey" PRIMARY KEY, btree (r_id)
Foreign-key constraints:
    "received_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)

testdb=> \d attach
                             Table "public.attach"
 Column |  Type   | Collation | Nullable |               Default                
--------+---------+-----------+----------+--------------------------------------
 a_id   | integer |           | not null | nextval('attach_a_id_seq'::regclass)
 m_id   | integer |           | not null | nextval('attach_m_id_seq'::regclass)
 attach | text    |           | not null | 
Indexes:
    "attach_pkey" PRIMARY KEY, btree (a_id)
Foreign-key constraints:
    "attach_m_id_fkey" FOREIGN KEY (m_id) REFERENCES overview(m_id)

```

2021-09-30 06:58 UTC, merged