メールから本文を読み込み，patternと比較する機能の実装
security-anthem/MAID pull request #22
Opened 2021-10-02 22:58 UTC by maplizm

## Issue
#15

## 内容
1. ファイル追加
    - `analyze_text.js`(メールの本文をデコードし，本文中に特定のパターン文字列が含まれているかチェックする)
    - メール本文のエンコード方式は base64，quoted-printable，8bit，7bitが想定される
    - メールの文字コードは utf-8，iso-2022-jp(JIS)が想定される
    - メールの構成は マルチパート方式，テキストメール，HTMLメールが想定される
    - 以上を考慮し，正しくメール本文をデコードするよう条件分岐を設定
    - 現在未完了の項目は，エンコード方式：quoted-printable，文字コード：iso-2022-jpの組み合わせの場合のデコード，メール本文に含まれていたパターンの情報をDBに格納する機能の実装
2. 1.のjsファイル追加に伴い，`index.tpl`でjsファイルが読み込まれるよう記述内容を追加
3. 1.のjsファイル追加に伴い，`read_file.js`で追加した関数が呼び出されるよう記述内容を追加

## 確認方法
- `views/index.tpl`をこのプロジェクトのトップにコピーし，`index.html`に改名
- `static/read_file.js`の`makePostReqeust`の行をコメントアウト
- `index.html`をGoogle Chromeなどのブラウザで開き，日本語で書かれたメールを読み込ませる
- ブラウザの開発者画面のconsoleに，以下の項目が出力される．
  1. メールの形式
  2. boundary
  3. メール本文のエンコード方式
  4. デコード前のメール本文
  5. デコード後のメール本文
  6. メール本文中に含まれるパターン文字列のリスト
  ※以上の項目は動作確認用に出力するよう設定しており，システム運用時では出力しない想定である．
　

2021-10-04 16:46 UTC, eku0011 requested changes
気になった点が2つあります．


1つ目は，`static/analyze_text.js`の8行目

> `let strForSearch = 'Content-Type: multipart/alternative';`

に関して，以下のWebサイトを見ると，メールのマルチパートはmultipart/alternativeのみではないようです．

https://atmarkit.itmedia.co.jp/ait/articles/0104/18/news002.html

実際に添付ファイル付きメール(multipart/mixed形式)を読み込むと，メールの本文のみを抽出できていませんでした．

> `let strForSearch = 'Content-Type: multipart/';`

と書き換えれば解決できそうな気がします(確信はないです)．


2つ目は，`static/analyze_text.js`の35行目

> `encodedTextBody = textEml.slice(textBodyStart, textBodyEnd);`

に関して，`textBodyEnd`が未定義のまま使用されていると思います．

以上2点の確認よろしくお願いします．
multipart/alternative形式のメールとマルチパートでないメールに関しては，正常に動作したのを確認しました．

2021-10-05 07:51 UTC, maplizm commented
## 修正内容
差分については，以下のコミットを参照
27ae3e4

- multipart/mixed形式に対応できるように`analyze_text.js`の記述内容を変更
- 未定義の`textBodyEnd`をメールソースの末尾`textEml.length`として定義するよう変更

2021-10-06 10:23 UTC, shu1oka28 approved these changes
動作確認した結果、問題ありませんでした。

2021-10-06 10:24 UTC, shu1oka28 commented
残された課題として書かれている「現在未完了の項目は，エンコード方式：quoted-printable，文字コード：iso-2022-jpの組み合わせの場合のデコード，メール本文に含まれていたパターンの情報をDBに格納する機能の実装」があるため、issueはcloseしません。

2021-10-06 10:25 UTC, merged